version: "3.8"

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Oyewole2025
      MYSQL_DATABASE: mseet_39093726_felicity
      MYSQL_USER: mseet_39093726
      MYSQL_PASSWORD: Oyewole2025
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
